In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from torch import nn
import torch.nn.functional as F

np_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np_array.shape, np_array.ndim)

torch_array = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
print(torch_array.shape, torch_array.dim())

(2, 4) 2
torch.Size([2, 4]) 2


In [5]:
np_array = np.zeros([32, 64, 128])
np_array2 = np_array.reshape(128, 64, -1)

print(np_array.shape, np_array2.shape)

torch_array = torch.zeros([32, 64, 128])
torch_array2 = torch_array.view([128, 64, -1])
print(torch_array.shape, torch_array2.shape)

(32, 64, 128) (128, 64, 32)
torch.Size([32, 64, 128]) torch.Size([128, 64, 32])


In [2]:
w = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

print(w , b)
print(w.requires_grad, b.requires_grad)
print(w.grad, b.grad)

tensor([0.8517], requires_grad=True) tensor([0.4061], requires_grad=True)
True True
None None


In [3]:
x = torch.rand(1024)
y = 2.0 * torch.FloatTensor(x) + 5.0
w = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)
print(w, b)
print(w.grad, b.grad)

tensor([0.6889], requires_grad=True) tensor([0.1244], requires_grad=True)
None None


In [6]:
from torch.optim import SGD
opti = SGD([w, b], lr=1e-2)

for i in range(1000):
    h = w * x + b
    err = torch.mean((h - y) ** 2)

    opti.zero_grad() # Gradient 초기화
    err.backward() # Back Propagation
    opti.step() # Gradient Update

    if (i % 50) == 0:
        print(w, b)

tensor([0.7484], requires_grad=True) tensor([0.2354], requires_grad=True)
tensor([2.3625], requires_grad=True) tensor([3.3157], requires_grad=True)
tensor([2.7567], requires_grad=True) tensor([4.1783], requires_grad=True)
tensor([2.8218], requires_grad=True) tensor([4.4361], requires_grad=True)
tensor([2.8003], requires_grad=True) tensor([4.5279], requires_grad=True)
tensor([2.7576], requires_grad=True) tensor([4.5732], requires_grad=True)
tensor([2.7115], requires_grad=True) tensor([4.6046], requires_grad=True)
tensor([2.6667], requires_grad=True) tensor([4.6310], requires_grad=True)
tensor([2.6244], requires_grad=True) tensor([4.6548], requires_grad=True)
tensor([2.5846], requires_grad=True) tensor([4.6769], requires_grad=True)
tensor([2.5473], requires_grad=True) tensor([4.6976], requires_grad=True)
tensor([2.5123], requires_grad=True) tensor([4.7169], requires_grad=True)
tensor([2.4796], requires_grad=True) tensor([4.7349], requires_grad=True)
tensor([2.4490], requires_grad=True) t